#!/bin/bash

THEBIB=./bibfile.bib
BKPBIB=./bibfile.bkp

function help() {
    cat << ____EOF
NAME
    bib - perform atomic bib operations

SYNOPSIS
    bib COMMAND [args]
        where COMMAND is one of:
            help (no args)
                Print this and exits.
            LIST (no args)
                Lists keys on the default bibfile ./bibfile.bib initializing  it
                if needed.
            LST (no args)
                Generates a machine-readable list of keys from  default  bibfile
                ./bibfile.bib initializing it if needed.
            BASE (no args)
                Lists the accessible bibliography database, one file per line.
            ADD <bibpats>
                Backs  up  ./bibfile.bib  into  ./bibfile.bkp,  then  adds   all
                bibliographic entries  from  files  matching  each  one  of  the
                <bibpats>  (no  wildcards),  if   existing,   to   the   default
                ./bibfile.bib.
            REM <bibpats>
                Backs up ./bibfile.bib into  ./bibfile.bkp,  then  rebuilds  the
                default ./bibfile.bib from scratch from previous list  of  keys,
                avoiding each one of the <bibpats> patterns (no  wildcards).
            RESET
                Backs up  ./bibfile.bib  into  ./bibfile.bkp,  then  resets  the
                ./bibfile.bib into an empty file.

AUTHOR
    Naaktgeboren, C.
____EOF
    exit ${1:--1};
}

# Argument check
if test "a${1}" == "a"; then
    echo -e "ERROR: not enough arguments.\n"
    help -1;
fi

# Functionality

function uline() {
    MSG="$(echo -e ${1})"
    echo "${MSG}"
    echo "${MSG}" | sed 's|.|-|g'
}

function hasBib() { test -f "${THEBIB}"; }
function hasBkp() { test -f "${BKPBIB}"; }
function hasBoth() { hasBib && hasBkp; }

function preQuery() {
    if hasBib; then
        echo -e "INFO: Existing '${THEBIB}'";
    elif hasBkp; then
        echo -e "INFO: Restored missing '${THEBIB}' from '${BKPBIB}'"
        cp -f "${BKPBIB}" "${THEBIB}";
    else
        echo -e "INFO: Created empty '${THEBIB}'"
        cp -f /dev/null "${THEBIB}";
    fi;
}

function preChange() {
    if hasBib; then
        echo -e "INFO: Backing up existing '${THEBIB}' into '${BKPBIB}'";
        cp -f "${THEBIB}" "${BKPBIB}"
    elif hasBkp; then
        echo -e "INFO: Restored missing '${THEBIB}' from '${BKPBIB}'"
        cp -f "${BKPBIB}" "${THEBIB}";
    else
        echo -e "INFO: Missing '${THEBIB}' and '${BKPBIB}'. Created empty ones."
        cp -f /dev/null "${THEBIB}";
        cp -f /dev/null "${BKPBIB}";
    fi;
}

function _listBib() {
    uline "Key list for file '${THEBIB}':"
    grep '^@' "${THEBIB}" |\
        grep -v '^@Comment' |\
        sort -n |\
        sed 's|^|\t|g';
}

function _lstBib() {
    grep '^@' "${THEBIB}" |\
        grep -v '^@Comment' |\
        sed 's|^.*{||g' |\
        sed 's|, *$||g' |\
        sort -n;
}

function listBib() {
    if [ "$#" -lt 1 ]; then
        _listBib;
    else
        _listBib | grep "$1";
    fi
}

function lstBib() {
    if [ "$#" -lt 1 ]; then
        _lstBib;
    else
        p="$1"
        shift
        lstBib "$@" | grep "$p";
    fi
}

function dbase() {
    find -L . -name '*\.bib' | grep -v "${THEBIB}" | sort -n
}

function dbfiles() {
    for i in $(dbase); do basename "${i}"; done
}

function keysOf() {
    FULPTH="$(find -L . -name ${1}.bib)"
    grep '^@' "${FULPTH}" |\
        grep -v '^@Comment' |\
        sed 's|^.*{||g' |\
        sed 's|, *$||g' |\
        sort -n;
}

function addBib() {
    if [ "$#" -lt 1 ]; then
        echo -e "ERROR: Missing arguments to ADD.\n"
        help -1;
    fi
    for BIBPAT in "$@"; do
        for BIBSRC in $(dbfiles | sed "s|\.bib$||g" | grep "${BIBPAT}"); do
            if grep -q "$(keysOf ${BIBSRC})" "${THEBIB}"; then
                for BIBKEY in $(keysOf ${BIBSRC}); do
                    echo -e "INFO: x '${BIBKEY}' (from ${BIBSRC})."
                done;
            else
                for BIBKEY in $(keysOf ${BIBSRC}); do
                    echo -e "INFO: + '${BIBKEY}' (from ${BIBSRC})."
                done;
                cat $(find -L . -name "${BIBSRC}.bib") >> "${THEBIB}"
                echo "" >> "${THEBIB}";
            fi
        done
    done
}

function remBib() {
    CURKEY="$(./bib LST)"
    REMKEY="$(echo $@ | sed 's| |\n|g')"
    DIFKEY="$(echo "${CURKEY}" | grep -v "${REMKEY}")"
    echo -e "INFO: x ALL KEYS."
    cp /dev/null "${THEBIB}"
    addBib "${DIFKEY}"
}

function sortBib() {
    echo -e "INFO: Sorting '${THEBIB}'";
    remBib "$(md5sum ${THEBIB} | cut -f1 -d' ')"
}

function bibBkp() {
    if hasBib; then
        echo -e "INFO: Backing up '${THEBIB}' into '${BKPBIB}'"
        cp -f "${THEBIB}" "${BKPBIB}";;
    else
        echo -e "INFO: Nothing to backup"
    fi
}

# MAIN - Parse commands
COMM="${1}"
shift
case "${COMM}" in
    #----------------------------------------------------------------------#
    #                              No-DB opts                              #
    #----------------------------------------------------------------------#
    "help" | "HELP")
        help 0;;
    #----------------------------------------------------------------------#
    #                           Remote DBs opts                            #
    #----------------------------------------------------------------------#
    "BASE")
        dbase;;
    #----------------------------------------------------------------------#
    #                              Query opts                              #
    #----------------------------------------------------------------------#
    "LIST")
        preQuery
        listBib "$@";;
    "LST")
        preQuery
        lstBib "$@";;
    #----------------------------------------------------------------------#
    #                            Local DB opts                             #
    #----------------------------------------------------------------------#
    "ADD")
        preChange
        addBib "$@";;
    "BACKUP")
        preChange
        bibBkp;;
    "REM")
        cp "${THEBIB}" "${BKPBIB}"
        remBib "$@";;
    "RESET")
        cp "${THEBIB}" "${BKPBIB}"
        cp /dev/null "${THEBIB}";;
    "SORT")
        cp "${THEBIB}" "${BKPBIB}"
        sortBib "$@";;
    #----------------------------------------------------------------------#
    #                               Invalid                                #
    #----------------------------------------------------------------------#
    *)
        echo -e "ERROR: invalid command: '${1}'.\n"
        help -1;;
esac

