#!/bin/bash

function yrefs() {
    bib LST $1 2>/dev/null | paste -s -d'#' | sed 's|#$||g;s|#|, |g'
}

for y in $(years); do
    if test "$y" != "2020"; then
        echo "\\textbf{$y}: \\cite{$(yrefs $y)},"
    else
        echo "\\textbf{$y}: \\cite{$(yrefs $y)}."
    fi
done

